### ISSUE TITLE
Font support

### ISSUE THREAD

**Issue by allenck** [tuupola/hagl_esp_mipi#11]
Have you given any thought to providing support for Truetype fonts. I am using PlatformIO and could not manage to compile it. They do some funny things like using defines to declare the names of include files.

**Comment by tuupola** [comment]
I do not have plans to support TrueType fonts at the moment. I mostly target small screens and I personally think TrueType is a bit bloated format. FONTX format, albeit rarely used in western world, is quite awesome. I have a repository with the [X11](https://github.com/tuupola/embedded-fonts/tree/master/X11) and [unscii](https://github.com/tuupola/embedded-fonts/tree/master/misc/viznut) fonts in the FONTX format. Will add more later.

Adding support for for PlatformIO is in my TODO list. But since I do not use PlatformIO myself it has stayed in the backlog. Now that you remind me about I should take a look at it again.

**Comment by allenck** [comment]
I can certainly understand that you would like to not support True Type. There are some issues with PlatformIO that need to be addressed. Mainly, there is the issue of providing user options since PlatformIO does not have a menuconfig command. I solved this by adding the defines in a header file that was included in hagl_hal.h.

**Comment by allenck** [comment]
I can certainly understand that you would like to not support True Type. There are some issues with PlatformIO that need to be addressed. Mainly, there is the issue of providing user options since PlatformIO does not have a menuconfig command. I solved this by adding the defines in a header file that was included in hagl_hal.h.

**Comment by tuupola** [comment]
I am planning to do something similar as with the [main library config](https://github.com/tuupola/hagl/blob/master/include/config.h). Meaning that user could either manually edit the config file or alternatively use menuconfig when it is available. I just need to familiarise myself with PlatformIO a bit first.
